name: calories_calculator

services:
  postgres:
    image: postgres:18
    env_file: .env
    volumes:
      - calories_calculator_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
      start_interval: 1s
    restart: always

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      SWAGGER_UI_ADDR: http://localhost:8080
    configs:
      - source: http_config
        target: app/config/backend.json
      - source: JWT-key
        target: app/config/HS256key.txt
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/static:ro
    depends_on:
      - backend
    restart: always
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./docs/OpenAPI/openapi.yaml:/docs/openapi.yaml
    depends_on:
      - backend
    stop_grace_period: 0s
    restart: always

volumes:
  calories_calculator_data:

configs:
  http_config:
    file: config/backend.json
  JWT-key:
    file: config/HS256key.txt
