server {
    server_name frontend;

    location / {
        root /static/html;
        index index.html;

        try_files $uri $uri.html $uri/ =404;
    }

    location /api/ {
        proxy_pass http://backend:8000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}